name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3

      - id: debian-new-cloud-releases
        name: New releases
        env:
          DEBIAN_VERSION: 12
          DEBIAN_VERNAME: bookworm
          DEBIAN_RELEASE: 20231210-1590
        run: |
          # Releases
          releases=$(
            curl -s "https://cloud.debian.org/images/cloud/$DEBIAN_VERNAME/" | \
            sed -nr 's/.+<a href="([0-9]{8}-[0-9]{4})\/.+/\1/p' |
            sed -e "1,/$DEBIAN_RELEASE/d"
          )
          echo "$releases" > releases.out
          echo "$releases"

      - name: Summary
        run: |
          cat >> "$GITHUB_STEP_SUMMARY" <<-EOF
            ### New releases! :rocket:

          EOF

          while read release; do
            echo "* [$release](https://cloud.debian.org/images/cloud/bookworm/$release/)"
          done < "releases.out" >> $GITHUB_STEP_SUMMARY

          exit 1
